1.1.24:
  time_line: [2020-11-10]
  upgrade_modules:
    - phd_account
    - phd_stock
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Charge Credit Card

1.1.23:
  time_line: [2020-10-15]
  upgrade_modules:
    - phd_account_reports
    - phd_account
    - phd_stock
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - General Ledger Extended

1.1.22:
  time_line: [2020-09-23]
  upgrade_modules:
    - phd_account_reports
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - General Ledger Extended

1.1.21:
  time_line: [2020-09-22]
  upgrade_modules:
    - phd_sps_integration
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Fixtiny bug for SPS 810

1.1.20:
  time_line: [2020-09-22]
  upgrade_modules:
    - phd_sps_integration
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - SPS Improvements for vitamin shoppe

1.1.19:
  time_line: [2020-09-21]
  upgrade_modules:
    - phd_sps_integration
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - SPS Improvements for vitamin shoppe

1.1.18:
  time_line: [2020-09-07]
  upgrade_modules:
    - phd_mrp
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Resolve Conflict

1.1.17:
  time_line: [2020-09-07]
  upgrade_modules:
    - phd_mrp
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Resolve Conflict

1.1.16:
  time_line: [2020-09-07]
  upgrade_modules:
    - phd_account
    - phd_mrp
    - phd_sps_integration
    - phd_stock
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Script Update Beet Royalty

1.1.15:
  time_line: [2020-09-07]
  upgrade_modules:
    - phd_account
    - phd_mrp
    - phd_sps_integration
    - phd_stock
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Script Update Beet Royalty

1.1.14:
  time_line: [2020-09-02]
  upgrade_modules:
    - phd_inventory
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Improvement for Product moves report

1.1.13:
  time_line: [2020-08-24]
  upgrade_modules:
    - phd_stock
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Inventory Report

1.1.12:
  time_line: [2020-08-13]
  upgrade_modules:
    - phd_mrp
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Update Extracost on MO

1.1.11:
  time_line: [2020-07-27]
  upgrade_modules:
    - phd_mrp
    - phd_purchase
    - phd_stock
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Release to Prod

1.1.10:
  time_line: [2020-07-27]
  upgrade_modules:
    - phd_sps_integration
    - phd_account
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - GNC Go-live

1.1.9:
  time_line: [2020-07-27]
  upgrade_modules:
    - phd_sps_integration
    - phd_account
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - GNC Go-live

1.1.8:
  time_line: [2020-07-23]
  upgrade_modules:
    - phd_sps_integration
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - GNC Go-live

1.1.7:
  time_line: [2021-07-16]
  upgrade_modules:
    - phd_sale
  install_modules:
  database:
    - PHD_PRODUCTION
  release_notes:
    - Remove Magento

1.1.6:
  time_line: [2021-04-15]
  upgrade_modules:
    - phd_mrp
    - phd_magento2_ept
    - odoo_magento2_ept
    - common_connector_library
    - phd_account
    - phd_inventory
    - phd_mrp
    - phd_sps_integration
    - phd_stock
  install_modules:
  database:
    - phd_production
  release_notes:
    - Improvement

1.1.5:
  time_line: [2020-03-31]
  upgrade_modules:
    - phd_mrp
  install_modules:
  database:
    - phd_production
  release_notes:
    - Improve Subcontracting flow

1.1.4:
  time_line: [2020-03-26]
  upgrade_modules:
    - phd_mrp
  install_modules:
  database:
    - phd_production
  release_notes:
    - Improve Subcontracting flow

1.1.3:
  time_line: [2020-03-25]
  upgrade_modules:
    - phd_sps_integration
    - phd_account
    - phd_export_pdf
    - phd_tools
    - phd_sale
    - phd_purchase
    - phd_inventory
    - phd_mrp
    - phd_stock
    - phd_tracking
  install_modules:
    - phd_account_reports
  database:
    - phd_production
  release_notes:
    - Improve SPS Integration and Account report

1.1.2:
  time_line: [2020-02-25]
  upgrade_modules:
    - phd_sps_integration
    - phd_mrp
  install_modules:
  database:
    - phd_production
  release_notes:
    - Implement EDI 855 and Add PO cost to Cost Analysis

1.1.1:
  time_line: [2020-01-29]
  upgrade_modules:
    - phd_purchase
    - phd_inventory
  install_modules:
  database:
    - phd_pro
  release_notes:
    - Improve shipping address of PO report

1.1.0:
  time_line: [2020-01-25]
  upgrade_modules:
    - phd-sale
    - phd-purchase
    - phd_account
    - phd_stock
    - phd_inventory
    - phd_mrp
  install_modules:
  database:
    - PHD-PRODUCTION
  release_notes:
    - Improve SO and PO report and upgrade needed module

1.0.9:
  time_line: [2020-01-19]
  upgrade_modules:
    - phd_account
  install_modules:
  database:
    - phd-production
  release_notes:
    - Small fix in account type

1.0.8:
  time_line: [2020-01-19]
  upgrade_modules:
    - phd_mrp
  install_modules:
    - remove_decimal_zero_trailing
  database:
    - phd-production
  release_notes:
    - Improve Subcontracting flow by adding check available current stock

1.0.7:
  time_line: [2020-01-14]
  upgrade_modules:
    - phd_mrp
    - phd_purchase
    - phd_sale
  install_modules:
  database:
    - phd-production
  release_notes:
    - Improve Subcontracting flow and small fix in PO and SO report

1.0.6:
  time_line: [2020-01-12]
  upgrade_modules:
    - phd_mrp
  install_modules:
  database:
    - phd-production
  release_notes:
    - Improve Subcontracting flow

1.0.5:
  time_line: [2020-01-11]
  upgrade_modules:
    - phd_purchase
    - phd_sale
  install_modules:
    - remove_decimal_zero_trailing
  database:
    - phd-production
  release_notes:
    - Improve PO and SO report

1.0.4:
  time_line: [2020-01-07]
  upgrade_modules:
    - phd_mrp
    - phd_inventory
    - phd_stock
  install_modules:
  database:
    - phd-production
  release_notes:
    - Add constraint for producing process in MO and fix recommend Lot feature

1.0.3:
  time_line: [2020-01-06]
  upgrade_modules:
    - phd_stock
  install_modules:
  database:
    - phd-production
  release_notes:
    - Add Journal entry for consumable component

1.0.2:
  time_line: [2020-01-05]
  upgrade_modules:
    - phd_stock
    - phd_mrp
  install_modules:
  database:
    - phd-production
  release_notes:
    - Fix wrong produced quantity on MO when validating Receipt

1.0.1:
  time_line: [2020-12-23]
  upgrade_modules: 
  install_modules:
  database:
    - phd-production
  release_notes:
    - DevOps Team Apply Upgrade Module
