{
    "name": "Cash Flow Projection",
    "summary": "Cash Flow Projection",
    "version": "1",
    "author": "Novobi",
    "website": "https://www.novobi.com/",
    "description": """Cash Flow Projection is a part of Accounting Finance For E-Retailers""",
    "depends": [
        # 'account_partner_deposit',
        # 'purchase_partner_deposit',
        # 'sale_partner_deposit',
        'purchase',
        'sale',
        'account_reports',
        'account_dashboard',
    ],
    "data": [
        'security/ir.model.access.csv',
        'data/cash_flow_transaction_type.xml',
        'views/assets.xml',
        'views/cash_flow_projection_view.xml',
        'views/cash_flow_transaction_type_view.xml',
        'views/res_config_settings.xml',
        'views/account_account_view.xml',
        'views/cash_flow_projection_detail_report_view.xml',
        'views/report_financial.xml',
        'views/account_dashboard_views.xml',
        'wizard/so_po_lead_time_view.xml',
        'wizard/cash_flow_period_number_view.xml',
        'wizard/recurring_cash_settings_view.xml',
        'report/cash_flow_projection_template.xml',
    ],
    'qweb': ['static/src/xml/cash_flow_projection_backend.xml'],
    "application": False,
    "installable": True,
}
